### ISSUE TITLE
Build broken with undefined zerolog.LevelWidth

### ISSUE THREAD

**Issue by pmundt** [danielgtaylor/openapi-cli-generator#14]
With more recent versions of the zerolog package, LevelWidth has been removed, and so this no longer builds:

```
$ go build
# github.com/danielgtaylor/openapi-cli-generator/cli
../../../go/src/github.com/danielgtaylor/openapi-cli-generator/cli/log.go:60:6: undefined: zerolog.LevelWidth
../../../go/src/github.com/danielgtaylor/openapi-cli-generator/cli/log.go:61:18: undefined: zerolog.LevelWidth
../../../go/src/github.com/danielgtaylor/openapi-cli-generator/cli/log.go:64:21: undefined: zerolog.LevelWidth
```
More specifically, this was broken by the recent rewriting of the [zerolog.ConsoleWriter interface](https://github.com/rs/zerolog/commit/96f91bb4f5dae9f5026ed08500dd8692f9cdf67b#diff-b0d3ae5e607395dec491b715aea0e01b).

**Comment by mitchtbaum** [comment]
@danielgtaylor do you have any ETA for this?

**Comment by geekodour** [comment]
@pmundt this can be fixed by using the version before that PR was introduced. by using go modules and locking the vendor directory. It will also prevent this from happening in the future with other dependencies. ?
