### ISSUE TITLE
loader.LoadSwaggerFromYAMLData undefined

### ISSUE THREAD

**Issue by danielklim** [danielgtaylor/openapi-cli-generator#19]
Go get fails with:
`/main.go:479:24: loader.LoadSwaggerFromYAMLData undefined (type *openapi3.SwaggerLoade
r has no field or method LoadSwaggerFromYAMLData)`

In https://github.com/getkin/kin-openapi/commit/82a13f94c08e2a85812f8b0d4f971e22d86b7203, getkin library changed the `LoadSwaggerFromYAMLData` to a generic `LoadSwaggerFromData` so theoretically, just changing the function call in line 479 should fix this error.

**Comment by danielgtaylor** [comment]
Fixed in 5f5c1b3f44f2d5f538a9379688db215c2691bf02
