### ISSUE TITLE
openapi-cli-generator init <app-name> not working MacOS

### ISSUE THREAD

**Issue by dhavalgogri17** [danielgtaylor/openapi-cli-generator#22]
I successfully installed go and then used the "go get -u github.com/danielgtaylor/openapi-cli-generator" you gave. 
But the init command doesn't work. 
Gives me the following error on MacOS Terminal:
-bash: openapi-cli-generator: command not found

**Comment by falzm** [comment]
@dhavalgogri17 if you haven't set a `GOPATH` environment variable, the `go get ...` command mentioned in the documentation has probably created a `go/` directory in your current user home directory. The `openapi-cli-generator` binary should be located in `~/go/bin/openapi-cli-generator` ; you should add something like this in your shell configuration (I'm assuming you're running Bash):

```sh
export PATH="${PATH}:${HOME}/go/bin"
```

**Comment by danielgtaylor** [comment]
I believe @falzm's comment shows you how to fix your issue, so I'm going to close this. Please re-open if needed!
